replicaCount: 1
autoscaling:
  enabled: false

image:
  repository: ghcr.io/toboshii/hajimari
  pullPolicy: IfNotPresent
  tag: v0.2.0

# -- environment variables.
env:
  TZ: Europe/Moscow

# -- Configures Hajimari settings for this instance.
hajimari:
  # -- The name of this instance, this allows running multiple
  # instances of Hajimari on the same cluster
  instanceName: null
  # -- Set to true to show all discovered applications by default.
  defaultEnable: false
  # -- Namespace selector to use for discovering applications
  namespaceSelector:
    matchNames:
      - kube-system
  # -- Override the title of the Hajimari pages
  title: LibrePod Start Page
  name: "LibrePod User"
  # -- Add custom applications to the discovered application list
  customApps: []
  # - name: Test
  #   url: https://example.com
  #   icon: test-tube

  # -- Set default bookmarks
  groups: []
  # - name: Communicate
  #   links:
  #   - name: Discord
  #     url: 'https://discord.com'
  #   - name: Gmail
  #     url: 'http://gmail.com'
  #   - name: Slack
  #     url: 'https://slack.com/signin'


# -- Configures service settings for the chart.
service:
  port: 3000
  targetPort: 3000

# -- Configures service account needed for reading k8s ingress objects
serviceAccount:
  create: true

ingress:
  enabled: true
  domain: libre.pod

# -- Configure persistence settings for the chart under this key.
persistence:
  enabled: true
  size: 100Mi
