image:
  repository: mvance/unbound
  pullPolicy: IfNotPresent
  tag: ""

service:
  main:
    enabled: true
    clusterIP: 10.43.111.111
    ports:
      http:
        enabled: false
      dns:
        enabled: true
        primary: true
        port: 5353
        protocol: UDP
        targetPort: 53

env:
  TZ: Europe/Moscow

persistence:
  forward-records:
    enabled: true
    size: 10Mi
    name: '{{ include "librepod.names.fullname" . }}-forward-records'
    mountPath: /opt/unbound/etc/unbound/forward-records.conf
    subPath: forward-records.conf
    type: configMap

configmap:
  forward-records:
    enabled: true
    data:
      forward-records.conf: |
        # Leaving this file blank since we want to resolve
        # DNS queries by unbound itself.
