{{/*
Main entrypoint for the librepod library chart. It will render all underlying templates based on the provided values.
*/}}
{{- define "librepod.all" -}}
  {{- /* Merge the local chart values and the librepod chart defaults */ -}}
  {{- include "librepod.values.setup" . }}

  {{ include "librepod.configmap" . | nindent 0 }}

  {{- /* Build the templates */ -}}
  {{- include "librepod.pvc" . }}

  {{- if .Values.serviceAccount.create -}}
    {{- include "librepod.serviceAccount" . }}
  {{- end -}}

  {{- if .Values.controller.enabled }}
    {{- if eq .Values.controller.type "deployment" }}
      {{- include "librepod.deployment" . | nindent 0 }}
    {{ else if eq .Values.controller.type "daemonset" }}
      {{- include "librepod.daemonset" . | nindent 0 }}
    {{ else if eq .Values.controller.type "statefulset"  }}
      {{- include "librepod.statefulset" . | nindent 0 }}
    {{ else }}
      {{- fail (printf "Not a valid controller.type (%s)" .Values.controller.type) }}
    {{- end -}}
  {{- end -}}

  {{ include "librepod.service" . | nindent 0 }}

  {{ include "librepod.ingressroute" . | nindent 0 }}

  {{ include "librepod.forecastleapp" . | nindent 0 }}

{{- end -}}
