{{- define "librepod.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "librepod.names.fullname" . }}
  labels:
    {{- include "librepod.names.labels" . | nindent 4 }}
data: {}
{{- end -}}

{{- define "librepod.configmap" -}}
{{- include "librepod.util.merge" (append . "librepod.configmap.tpl") -}}
{{- end -}}
