{{/* Renders the Ingress objects required by the chart */}}

{{/*
This template serves as a blueprint for all Ingress objects that are created
within the librepod library.
*/}}

{{/* Renders the IngressRoute objects required by the chart */}}
{{- define "librepod.ingressroute" -}}
  {{- /* Generate named ingresses as required */ -}}
  {{- range $name, $ingress := .Values.ingress }}
    {{- if $ingress.enabled -}}
      {{- $ingressValues := $ingress -}}

      {{/* set defaults */}}
      {{- if and (not $ingressValues.nameOverride) (ne $name (include "librepod.ingress.primary" $)) -}}
        {{- $_ := set $ingressValues "nameOverride" $name -}}
      {{- end -}}

      {{- $_ := set $ "ObjectValues" (dict "ingress" $ingressValues) -}}
      {{- include "librepod.classes.ingress" $ }}
    {{- end }}
  {{- end }}
{{- end }}

{{/* Return the name of the primary ingress object */}}
{{- define "librepod.ingress.primary" -}}
  {{- $enabledIngresses := dict -}}
  {{- range $name, $ingress := .Values.ingress -}}
    {{- if $ingress.enabled -}}
      {{- $_ := set $enabledIngresses $name . -}}
    {{- end -}}
  {{- end -}}

  {{- $result := "" -}}
  {{- range $name, $ingress := $enabledIngresses -}}
    {{- if and (hasKey $ingress "main") $ingress.main -}}
      {{- $result = $name -}}
    {{- end -}}
  {{- end -}}

  {{- if not $result -}}
    {{- $result = keys $enabledIngresses | first -}}
  {{- end -}}
  {{- $result -}}
{{- end -}}
