{{/*
The ServiceAccount object to be created.
*/}}
{{- define "librepod.serviceAccount" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "librepod.names.serviceAccountName" . }}
  labels: {{- include "librepod.labels" $ | nindent 4 }}
  {{- with (merge (.Values.serviceAccount.annotations | default dict) (include "librepod.annotations" $ | fromYaml)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
