{{- define "librepod.storage" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "librepod.names.pvcName" . }}
  labels:
    {{- include "librepod.names.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ default "nfs-client" .Values.persistence.storageClassName }}
  accessModes: {{ default (list "ReadWriteOnce") .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
