image:
  repository: zadam/trilium
  pullPolicy: IfNotPresent
  tag: ""

persistence:
  config:
    enabled: false
  data:
    enabled: true
    type: pvc
    mountPath: /data
    readOnly: false
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true

env:
  TRILIUM_DATA_DIR: "/data"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        primary: true
        port: 8080

ingress:
  main:
    enabled: true
    hosts:
      - host: trilium.libre.pod

dashboard:
  expose: true
  group: My Apps
