apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "librepod.names.fullname" . }}
  labels:
    {{- include "librepod.names.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "librepod.names.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "librepod.names.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "librepod.names.pvcName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "librepod.names.fullname" . }}
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql
              subPath: data
