# The 'hostIP' is supposed to be set upon chart installation:
# helm install pihole --set hostIP="192.168.1.200"
hostIP: 127.0.0.1

image:
  repository: lissy93/dashy
  pullPolicy: IfNotPresent
  tag: ""

env:
  NODE_ENV: production

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        primary: true
        port: 80

ingress:
  main:
    enabled: true
    hosts:
      - host: libre.pod
      - host: "{{ .Values.hostIP }}"

persistence:
  config:
    enabled: true
    type: configMap
    name: '{{ include "librepod.names.fullname" . }}-config'
    mountPath: /app/public/conf.yml
    subPath: conf.yml

# Dashy might consume high CPU utilization when iddle.
# See https://github.com/Lissy93/dashy/issues/969
# resources:
#   limits:
#     cpu: "0.5"
#     memory: "512Mi"
#   requests:
#     cpu: "0.2"
#     memory: "256Mi"

configmap:
  config:
    enabled: true
    data:
      conf.yml: |
        # Page meta info, like heading, footer text and nav links
        pageInfo:
          title: LibrePod
          description: Welcome to LibrePod Dashboard!
        # navLinks:
        # - title: GitHub
        #   path: https://github.com/librepod/librepod
        # - title: Documentation
        #   path: https://librepod.ru

        # Optional app settings and configuration
        appConfig:
          theme: one-dark
          routingMode: hash

        # Main content - An array of sections, each containing an array of items
        sections:
        - name: Getting Started
          icon: fas fa-rocket
          items:
          - title: Dashy Live
            description: Configure access to your LibrePod instance via Wireguard
            icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
            url: https://wireguard.libre.pod

          - title: GitHub
            description: Source Code, Issues and Pull Requests
            url: https://github.com/librepod/librepod
            icon: favicon

          - title: Docs
            description: Configuring & Usage Documentation
            provider: Dashy.to
            icon: far fa-book
            url: https://dashy.to/docs

          - title: Showcase
            description: See how others are using Dashy
            url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
            icon: far fa-grin-hearts

          - title: Config Guide
            description: See full list of configuration options
            url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
            icon: fas fa-wrench

          - title: Support
            description: Get help with Dashy, raise a bug, or get in contact
            url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
            icon: far fa-hands-helping
