---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: step-ca-bootstrap
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: step-ca-bootstrap-role
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: step-ca-bootstrap-rolebinding
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
subjects:
- kind: ServiceAccount
  name: step-ca-bootstrap
roleRef:
  kind: Role
  name: step-ca-bootstrap-role
  apiGroup: rbac.authorization.k8s.io
