# The 'hostIP' is supposed to be set upon chart installation:
# helm install pihole --set hostIP="192.168.1.200"
hostIP: 127.0.0.1

image:
  repository: adguard/adguardhome
  pullPolicy: IfNotPresent
  tag: ""

# Arguments passed to the adguard-home command line.
args:
  - "/opt/adguardhome/AdGuardHome"
  - "--config"
  - "/opt/adguardhome/conf/AdGuardHome.yaml"
  - "--work-dir"
  - "/opt/adguardhome/work"
  - "--no-check-update"

env:
  TZ: Europe/Moscow

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        primary: true
        port: 80
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        port: 53
        protocol: UDP

ingress:
  main:
    enabled: true
    hosts:
      - host: adguard.libre.pod

dashboard:
  expose: true
  url: "https://adguard.libre.pod"

# Configures an initContainer that copies initial config from the configmap to
# the AdGuardHome conf directory.
# It does NOT overwrite when the file already exists.
initContainers:
  - name: configmap-updater-container
    image: busybox:1.28
    command:
      - sh
      - -c
      - |
        echo "🤙 Aloha from the init container!"
        if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
          mkdir -p /opt/adguardhome/conf
          cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
          echo "Initial config has been copied!"
        fi
        cat /opt/adguardhome/conf/AdGuardHome.yaml
    volumeMounts:
    - name: adguardhome-config
      mountPath: /tmp/AdGuardHome.yaml
      subPath: AdGuardHome.yaml
    - mountPath: /opt/adguardhome/conf
      name: conf-data

persistence:
  config:
    enabled: false
  work-data:
    enabled: true
    type: pvc
    mountPath: /opt/adguardhome/work
    readOnly: false
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
  conf-data:
    enabled: true
    type: pvc
    mountPath: /opt/adguardhome/conf
    readOnly: false
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: true
  adguardhome-config:
    enabled: true
    size: 10Mi
    name: '{{ include "librepod.names.fullname" . }}-adguardhome-config'
    mountPath: /opt/adguardhome/conf/default/AdGuardHome.yaml
    subPath: AdGuardHome.yaml
    type: configMap

configmap:
  adguardhome-config:
    enabled: true
    data:
      # See here for config specs:
      # https://github.com/AdguardTeam/Adguardhome/wiki/Configuration#configuration-file
      AdGuardHome.yaml: |
        bind_host: 0.0.0.0
        bind_port: 80
        users:
          - name: admin
            password: $2a$10$mCwX0kjunP9uOkEfWWqSOeDJ.XqOssnfER7O2gKHfOdnujemQHI4u
        auth_attempts: 5
        block_auth_min: 15
        http_proxy: ""
        language: ""
        theme: auto
        debug_pprof: false
        web_session_ttl: 720
        dns:
          bind_hosts:
            - 0.0.0.0
          port: 53
          anonymize_client_ip: false
          protection_enabled: true
          blocking_mode: default
          blocking_ipv4: ""
          blocking_ipv6: ""
          blocked_response_ttl: 10
          protection_disabled_until: null
          parental_block_host: family-block.dns.adguard.com
          safebrowsing_block_host: standard-block.dns.adguard.com
          ratelimit: 20
          ratelimit_whitelist: []
          refuse_any: true
          upstream_dns:
            - 10.43.111.111:5353
          upstream_dns_file: ""
          bootstrap_dns:
            - 9.9.9.10
            - 149.112.112.10
            - 2620:fe::10
            - 2620:fe::fe:10
          all_servers: false
          fastest_addr: false
          fastest_timeout: 1s
          allowed_clients: []
          disallowed_clients: []
          blocked_hosts:
            - version.bind
            - id.server
            - hostname.bind
          trusted_proxies:
            - 127.0.0.0/8
            - ::1/128
          cache_size: 4194304
          cache_ttl_min: 0
          cache_ttl_max: 0
          cache_optimistic: false
          bogus_nxdomain: []
          aaaa_disabled: false
          enable_dnssec: false
          edns_client_subnet:
            custom_ip: ""
            enabled: false
            use_custom: false
          max_goroutines: 300
          handle_ddr: true
          ipset: []
          ipset_file: ""
          bootstrap_prefer_ipv6: false
          filtering_enabled: true
          filters_update_interval: 24
          parental_enabled: false
          safebrowsing_enabled: false
          safebrowsing_cache_size: 1048576
          safesearch_cache_size: 1048576
          parental_cache_size: 1048576
          cache_time: 30
          safe_search:
            enabled: true
            bing: true
            duckduckgo: true
            google: true
            pixabay: true
            yandex: true
            youtube: true
          rewrites:
            - domain: '*.libre.pod'
              answer: {{ .Values.hostIP }}
            - domain: libre.pod
              answer: {{ .Values.hostIP }}
          blocked_services: []
          upstream_timeout: 10s
          private_networks: []
          use_private_ptr_resolvers: true
          local_ptr_upstreams: []
          use_dns64: false
          dns64_prefixes: []
          serve_http3: false
          use_http3_upstreams: false
        tls:
          enabled: false
          server_name: ""
          force_https: false
          port_https: 443
          port_dns_over_tls: 853
          port_dns_over_quic: 853
          port_dnscrypt: 0
          dnscrypt_config_file: ""
          allow_unencrypted_doh: false
          certificate_chain: ""
          private_key: ""
          certificate_path: ""
          private_key_path: ""
          strict_sni_check: false
        querylog:
          ignored: []
          interval: 2160h
          size_memory: 1000
          enabled: true
          file_enabled: true
        statistics:
          ignored: []
          interval: 24h
          enabled: true
        filters:
          - enabled: true
            url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
            name: AdGuard DNS filter
            id: 1
          - enabled: false
            url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
            name: AdAway Default Blocklist
            id: 2
        whitelist_filters: []
        user_rules: []
        dhcp:
          enabled: false
          interface_name: ""
          local_domain_name: lan
          dhcpv4:
            gateway_ip: ""
            subnet_mask: ""
            range_start: ""
            range_end: ""
            lease_duration: 86400
            icmp_timeout_msec: 1000
            options: []
          dhcpv6:
            range_start: ""
            lease_duration: 86400
            ra_slaac_only: false
            ra_allow_slaac: false
        clients:
          runtime_sources:
            whois: true
            arp: true
            rdns: true
            dhcp: true
            hosts: true
          persistent: []
        log_file: ""
        log_max_backups: 0
        log_max_size: 100
        log_max_age: 3
        log_compress: false
        log_localtime: false
        verbose: false
        os:
          group: ""
          user: ""
          rlimit_nofile: 0
        schema_version: 20
