image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  tag: ""

persistence:
  config:
    enabled: false
  data:
    enabled: true
    type: pvc
    mountPath: /data
    readOnly: false
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true

env:
  SIGNUPS_ALLOWED: true
  INVITATIONS_ALLOWED: true
  # SERVER_ADMIN_EMAIL
  # DOMAIN
  # YUBICO_CLIENT_ID
  # YUBICO_SECRET_KEY
  # DATA_FOLDER
  # DATABASE_URL
  # ATTACHMENTS_FOLDER
  # ICON_CACHE_FOLDER
  # ROCKET_LIMITS
  # ROCKET_WORKERS
  # SMTP_HOST
  # SMTP_FROM
  # SMTP_PORT
  # SMTP_SSL
  # SMTP_EXPLICIT_TLS
  # SMTP_USERNAME
  # SMTP_PASSWORD
  # SHOW_PASSWORD_HINT
  # WEB_VAULT_ENABLED

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        primary: true
        port: 80

ingress:
  main:
    enabled: true
    hosts:
      - host: bitwarden.libre.pod

dashboard:
  expose: true
  url: "https://bitwarden.libre.pod"
