---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wg-easy
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 1
      services:
        - name: wg-easy
          port: 80
          passHostHeader: true
    - kind: Rule
      match: Host(`wg.libre.pod`)
      services:
        - name: wg-easy
          port: 80 
          passHostHeader: true
