{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "librepod.names.serviceAccountName" . }}
  labels:
    {{- include "librepod.labels" . | nindent 4 }}
rules:
- apiGroups: ["", "extensions", "networking.k8s.io"]
  resources: ["ingresses", "namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "librepod.names.serviceAccountName" . }}
  labels:
    {{- include "librepod.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "librepod.names.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "librepod.names.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
