bootstrap:
  secrets: false
  enabled: false
  configmaps: false

inject:
  enabled: false

existingSecrets:
  enabled: true
  ca: true
  issuer: true
  certsAsSecret: false
  configAsSecret: false
  sshHostCa: true
  sshUserCa: true

service:
  port: 9000

ca:
  name: LibrePod
  containerSecurityContext: {}
  db:
    enabled: false
  existingSecrets:
    enabled: true

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#           - key: node-group
#             operator: In
#             values:
#             - infra
