image:
  repository: cyxou/firefly-iii-telegram-bot
  pullPolicy: Always
  tag: ""

botParams:
  fireflyApiUrl: http://firefly-iii:8080
  fireflyUrl: https://firefly.libre.pod
  telegramBotToken: "<YOUR_TELEGRAM_BOT_TOKEN>"

env:
  TZ: "Europe/Moscow"
  DEBUG: "bot:*,firefly:axios:*"
  BOT_TOKEN: '{{ .Values.botParams.telegramBotToken }}'
  FIREFLY_URL: '{{ .Values.botParams.fireflyUrl }}'
  FIREFLY_API_URL: '{{ .Values.botParams.fireflyApiUrl }}'
  FIREFLY_ACCESS_TOKEN: '{{ .Values.botParams.fireflyAccessToken }}'

service:
  main:
    enabled: false

persistence:
  sessions:
    enabled: true
    type: pvc
    mountPath: /home/node/app/sessions
    readOnly: false
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: true
