apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-forward-records
data:
  forward-records.conf: |
    #forward-zone:
        # Forward all queries (except those in cache and local zone) to
        # upstream recursive servers
        #name: "."
        # Queries to this forward zone use TLS
        #forward-tls-upstream: yes

        # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

        ## Cloudflare
        #forward-addr: 1.1.1.1@853#cloudflare-dns.com
        #forward-addr: 1.0.0.1@853#cloudflare-dns.com
        # forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
        # forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com
