apiVersion: v1
kind: Service
metadata:
  name: {{ include "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
spec:
# type: {{ .Values.service.type }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
#   - port: 5353
#     targetPort: 53
#     protocol: TCP
#     name: dns-tcp
    - port: 5353
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "unbound.selectorLabels" . | nindent 4 }}
