image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: ""

persistence:
  config:
    enabled: false
  data:
    enabled: true
    type: pvc
    mountPath: /var/lib/postgresql/data
    readOnly: false
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true

env:
  PGPASSWORD: ""
  DBHOST: postgres-db
  DBPORT: "5432"
  DBNAME: postgres
  DBUSER: postgres
  TZ: Europe/Moscow
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        primary: true
        port: 5432
        targetPort: 5432
